dist: trusty
sudo: required

language: cpp

addons:
    apt:
        packages:
            - g++
            - gfortran
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - libboost-all-dev
            - libubsan0

before_install:
    - git clone -b maint https://bitbucket.org/petsc/petsc $HOME/petsc
    - cd $HOME/petsc && >
      ./configure PETSC_ARCH=arch-linux2-cxx-complex-debug --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-fblaslapack --with-clanguage=cxx --with-scalar-type=complex && >
      make PETSC_DIR=$HOME/petsc PETSC_ARCH=arch-linux2-cxx-complex-debug all

install:
    - export ANOMTRANS_DIR=$TRAVIS_BUILD_DIR
    - cd $TRAVIS_BUILD_DIR
    - ./build_test_local

script:
    - cd $TRAVIS_BUILD_DIR/Obj_test
    - ctest -V
